### ISSUE TITLE
Add compatibility with pgBouncer

### ISSUE THREAD

**Issue by asafyish** [graphile/worker#119]
Hi,

I would like to use graphile/worker in library mode with a pgBouncer in transaction mode, will it work correctly ?

**Comment by benjie** [comment]
Currently no, because it uses prepared statements and pgBouncer messes up prepared statements. I'd be open to a PR that makes the prepared statements optional though (just means adding a flag and removing the `name` from various places, e.g. https://github.com/graphile/worker/blob/f01c70f459085128c445749688f44ac503facb79/src/worker.ts#L88 ).
