### ISSUE TITLE
option to connect to existing db schema instead of creating new one

### ISSUE THREAD

**Issue by pangzineng** [graphile/worker#12]
## Feature Request
Allow the startup command to take an option to connect to an existing database schema. 

For example, in https://github.com/graphile/examples/blob/master/db/100_jobs.sql it's part of the overall database initialization, and with name `app_jobs`.

So it will be nice to be able to do something like this:
```
npx graphile-worker -c "postgres://localhost/mydb" -s "app_jobs"
```
which skip the schema creation steps and just start polling.

## Problem to Solve
Currently there is a depenency problem for **PostGraphile** user to make use of **graphile-worker**:

To add job within the main database code, such as `perform graphile_worker.add_job("send_mail", ...)`, the schema `graphile_worker` has to already exist at the moment of the main database schema creation, otherwise the sql will fail.

Therefore we always have to install **graphile-worker** before initializing the main db, even if we just want to add the job and leave it there.

And in my case, the database schema (pure sql) is handled by one team, and the job processing (pure javascript) is handled by another team. Such dependency is certainly going to generate a lot of unnecessary mess.

## Proposal
1. Skip the migration here if `-s` flag found
https://github.com/graphile/worker/blob/9793c512d0528b5dbfbfcbcaddbb838818e9651c/src/runner.ts#L52
2. Pass the `-s` value to all functions where sql query string were constructed, use the variable instead of hardcoded `graphile_worker`
https://github.com/graphile/worker/search?l=TypeScript&q=graphile_worker

**Comment by benjie** [comment]
This project is supposed to manage its own migrations/etc; the schema is not identical to the app_jobs schema and will likely evolve over time as we add new features. You can run with `--once` to just install the schema and exit, so I recommend you do that at database creation time/before migrations that depend on the worker. I don’t think we can commit to letting you use your own schema right now because it may mean that the project breaks on a minor update. I don’t want to have to do a major version bump every time we tweak the database schema.

**Comment by pangzineng** [comment]
Thanks, I understand your concern. 

There is probably some misunderstanding on my request. I'm not asking for the freedom to design my own schema, in fact I am using exactly https://github.com/graphile/worker/blob/master/sql/000001.sql, the only difference is the schema name `graphile_worker`. I can't imagine any minor or even major update that would break simply because the schema was not called `graphile_worker`. 

Also the decoupling of **installation** steps of db & node shouldn't cause any harm to the ongoing development of the project. However, triggering database setup from a nodejs module is considered harmful/bad practice to some DBAs out there (e.g. my team).

Anyway, I get your point and understand that you guys are busy with the more important things (which I like every much). I'll just fork and do it myself.

**Comment by joelmukuthu** [comment]
@benjie sorry to revive this again, but since some things have changed (referring to https://github.com/graphile/worker/pull/89),  do you foresee a case where this project needs more than the one schema? Would you be okay with approving a PR that changes the `create schema` to `create schema if not exists`? :)

**Comment by benjie** [comment]
We'll only ever need one schema. Please open a new issue to discuss.
