### ISSUE TITLE
`pollInterval` is mentioned in a code snippet in the README but not documented

### ISSUE THREAD

**Issue by benjie** [graphile/worker#15]

**Comment by madflow** [comment]
Since the pollIntervall PR was initially from me - I would be happy to pick this up. However under:

https://github.com/graphile/worker#running

all cli runner options are listed. `pollInterval` is equally good/bad documented like `once` or `jobs` I would say.  If PRs are welcome I would need a little bit more to go on ;).

**Comment by benjie** [comment]
The CLI options are documented okay, I think. It’s the library interface that lacks docs; even just saying “equivalent to CLI flag `--poll-interval`” would be a good start. Would you like to take that on? Also under the library docs we need to document run vs runOnce; hopefully the TypeScript types should make understanding them fairly straightforward.

**Comment by madflow** [comment]
> Would you like to take that on?

I can take a stab :crossed_swords: at it!
