### ISSUE TITLE
Cron API stability, 6 months later?

### ISSUE THREAD

**Issue by andrioid** [graphile/worker#203]
### Summary

I was looking into scheduled jobs and noticed **experimental** in the README and was wondering what the experience has been.

- Are we happy with the current API for cronjobs?
- Can we expect to upgrade from **experimental** to **beta**?
- If people decide to use it anyway; what kind of changes could we expect?

We were designing a task runner at work when I came across this project and it was both amazing and funny to see that you came to similar conclusions.

**Comment by benjie** [comment]
Hey, thanks for your interest!

No-one's reported any issues with cron functionality so I think it's definitely safe to use. The "experimental" is primarily to reserve my right to change the API (e.g. if I find performance edge cases that need addressing) rather than runtime stability concerns. That said, I've not discovered any such issues yet so I'll probably just jump straight to stable at some point :+1:

**Comment by dancernogorsky** [comment]
FWIW -
I am using the scheduled jobs in production on a critical monitoring system and have not had any issues.

I added a heartbeat task that sends an email to an external service which alerts me if an email is not received.
This was just a part of an e2e sanity check and to help me sleep at night.

**Comment by wokalski** [comment]
One thing I'd reconsider are the ergonomics of the library mode. The API is rather verbose and exposes the internals in a weird way (i.e. the commandment to always use `parseCronItems` makes it feel like it shouldn't even be a part of the public API)

**Comment by benjie** [comment]
Indeed; a restructure of the exposed API is something I plan to do before a 1.0.0 release. Mostly things are exposed purely for testing purposes, I was expecting most users to use the CLI version but it turns out that the library mode can be useful in quite a few circumstances. My plan is to remove all the current exposed APIs (except, probably, WorkerUtils) and replace them all with a facade that handles all the watch mode/etc complexities for you. Alas, as always, time is the enemy.
