### ISSUE TITLE
Connection terminated unexpectedly errors

### ISSUE THREAD

**Issue by MikeyBower93** [graphile/worker#225]
### Summary

We have been using graphile worker for quite a while now, however recently (over the past couple of weeks) we have receiving some db error log messages, specifically the following 2:
- `PostgreSQL active client generated error: Connection terminated unexpectedly`
- `Error with database notify listener: Connection terminated unexpectedly`

On first observation of these message we thought it might be due to the way we were interacting with the db with our application code, however we now believe this to be happening within the `graphile-worker` library, as we did the following:
```
    runner.events.on('pool:listen:error', ({error}) => {
        logger.error('graphile-worker-pool-error', error)
    })
```
in order to attach to any `graphile-worker` errors to see if this occurred at the same time as the other SQL errors we are getting, at which we do receive that message.

This doesn't seem to be causing any major issues as the `graphile-worker` process recovers and continues to process jobs, however we are not sure why it is occurring.

Thank you for any help.

### Additional context

- node version: `12.15.0`
- postgres version: `11.12`

**Comment by benjie** [comment]
I don't think we do anything internally that would cause these issues. Here's some potential causes:

- `pg` releases clients from the pool once they're released and have passed a certain age. Perhaps you're releasing a client from the pool and then using it? I wouldn't expect this to happen though because I think `pg` throws if you attempt this.
- Perhaps you have a firewall causing connection interruptions?
- Perhaps some of your instances are migrating hosts and the internet connections get interrupted?
- Perhaps you have a connection or session timeout and Postgres is terminating the connection?
- Perhaps you have a PostgreSQL connection pool in the mix and it's dropping connections at unexpected times?
- Perhaps you've got something triggering the connections to be terminated, e.g. a background cleanup task?
- Perhaps there's a netsplit situation in your hosting environment and the network routes between your Worker processes and your PostgreSQL server are getting interrupted?
- Perhaps your Worker or PostgreSQL instances run on boxes with connections that periodically reset, e.g. getting a new IP address or routing through different network uplinks?
- Perhaps your hosting provider is doing something funky...

Sorry I can't be more help, but AFAIK this isn't an issue caused by worker itself. Let me know if you find otherwise!

**Comment by benjie** [comment]
The likely reason for that is that you don't have a task definition that matches the identifiers of those jobs correctly. Check very carefully for typos and leading/trailing whitespace. Task identifiers are case sensitive.
