### ISSUE TITLE
Watch mode resolving npm workspace dependencies incorrectly

### ISSUE THREAD

**Issue by djmccormick** [graphile/worker#244]
### Summary

The watch mode of graphile-worker incorrectly resolves npm dependencies when using npm's workspaces when two different versions of a dependency are installed.

### Steps to reproduce

1. Create a new npm project using workspaces for "worker" and "other". Add different versions of Lodash to each workspace (4.17.21 for "other" and 4.17.20 for "worker") :

	```sh
	mkdir test
	cd test
	npm init -y
	npm init -w worker -y
	npm init -w other -y
	npm install graphile-worker --save-exact -w worker
	npm install lodash@4.17.21 --save-exact -w other
	npm install lodash@4.17.20 --save-exact -w worker
	printf "const _ = require('lodash');\nconsole.log('Lodash version in \"other\": ', _.VERSION);" > other/index.js
	mkdir -p worker/tasks
	printf "const _ = require('lodash');\nconsole.log('Lodash version in \"worker\": ', _.VERSION);" > worker/tasks/hello.js
	```
1. Create a `scripts.start` in `other/package.json`

	```json
	"start": "node index.js"
	```
1. Create `scripts.start` and `scripts.watch` in `worker/package.json`:

	```json
	"start": "graphile-worker",
	"watch": "graphile-worker --watch"
	```
1. See which version of Lodash "other" sees with `npm start`:

	```sh
	npm start -w other
	# Lodash version in "other":  4.17.21
	```
1. See which version of Lodash "worker" sees with `npm start` (ignore subsequent errors as we haven't set up graphile-worker):

	```sh
	npm start -w worker
	# Lodash version in "worker":  4.17.20
	```

1. See which version of Lodash "worker" sees with `npm run watch` (ignore subsequent errors as we haven't set up graphile-worker):
	```sh
	npm run watch -w worker
	# Lodash version in "worker":  4.17.21
	```

### Expected results

The version of Lodash seen in watch mode should be 4.17.20, as it is in normal mode.

### Actual results

The version of Lodash seen in watch mode is 4.17.21.

### Additional context

I'm using node v16.13.0 and npm v8.1.4. graphile-worker is at v0.12.2. I have seen this on my Mac and in official Node Docker images. It is not necessary to fully set up graphile-worker in order to see the issue (if you ignore the errors).

### Possible Solution

The "other" workspace had its Lodash installed first, and winds up installed at `./node_modules`. The "worker" workspace was second and has a different version, so npm installs it at `./worker/node_modules`. Presumably the watch mode could more closely mimic node's dependency resolution to resolve this issue.

**Comment by benjie** [comment]
Not ideal...

Could you trace through this file and see where it's going for your require of lodash? https://github.com/graphile/worker/blob/069c439109eb67862cba778506cbe9fee97d967e/src/module.ts#L18-L85 (You can do it by editing the file in `node_modules/graphile-worker/dist/module.js` and adding `console` statements, or by using a Node.js debugger e.g. `chrome://inspect` in Chrome.)

It should hit this block and thus defer to `require`:


https://github.com/graphile/worker/blob/069c439109eb67862cba778506cbe9fee97d967e/src/module.ts#L23-L28

But doing so... it should be using Node's module resolution because it's literally using `require` :wink: So clearly something has gone amiss somehow?

**Comment by benjie** [comment]
OH WAIT! Are you on Windows? Maybe it's `\\node_modules\\` on Windows!

**Comment by djmccormick** [comment]
Sorry, I have now updated the issue to say that I've seen this on my Mac locally as well as within Docker.

I added some console logs to check this out locally. As you predicted, we hit this block:
```js
    console.log('filename before', filename);
    if (filename.indexOf("/node_modules/") >= 0) {
        // Don't try and faux require node_modules (we only want one copy of these
        // in memory)
        console.log('A', filename.indexOf("/node_modules/"));
        return require(spec);
    }
```

My console outputs:
```
> worker@1.0.0 watch
> graphile-worker --watch

filename before /Users/foo/Projects/foo/test/worker/tasks/hello.js
filename before /Users/foo/Projects/foo/test/node_modules/lodash/lodash.js
A 43
```

**Comment by benjie** [comment]
Oh :facepalm: 

It's because it's calling `require` from _within_ graphile-worker (which must be installed to the root folder - having been hoisted by workspaces), rather than calling it from the context of your task.

Someone needs to change the fauxRequire implementation to accept the path of the task file, and then do something like:

```js
const filename = require.resolve(spec, { paths: [pathToTheTaskFile] }); 
if (filename.indexOf("/node_modules/") >= 0) { 
  // Don't try and faux require node_modules (we only want one copy of these 
  // in memory) 
  return require(filename); 
} 
```

(Changes: pass `paths` option to require.resolve, and pass `filename` rather than `spec` to `require`.)
