### ISSUE TITLE
Adding queueName to run()

### ISSUE THREAD

**Issue by danielbuechele** [graphile/worker#245]
I have multiple workers executing my tasks, but I need some jobs to run on certain servers only. I understand that this can currently be done using the `taskList` property.
The problem I am encountering with this approach is that I now need to have effectively different code on my worker nodes. If I could add a property `queueName` to the `run()` function, which only runs jobs from this queue, this could be easily configured via an env var, etc.
Does that sound like a reasonable idea? If so, I could try taking a stab at it.

**Comment by benjie** [comment]
Using the queues in this way isn't really desired; queues are for job control - serialization versus parallel - whereas your concern is regarding _where_ the jobs should run. This is a task identifier responsibility, not a queue name responsibility.

I'd be open to an additional argument such as `--only task1,task2,task3` to only run certain tasks.

**Comment by skabbes** [comment]
I wonder if exposing a library function to read a task list from a directory would facilitate a lot of these requests.


For example:

```javascript
// pseudo-code
import { run, readTaskListFromDir } from "graphile-worker";

const taskDirectory = `${__dirname}/tasks`;
const fullTaskList = await readTaskListFromDir(taskDirectory);

const myTaskList = _.omit(fullTaskList, 'ignoredTask1', 'ignoredTask2');
const runner = await run({
  taskList: myTaskList;
  //...
});

await runner.promise;

```

**Comment by benjie** [comment]
It's not currently documented (because I'm not 100% happy with the way it works in watch mode) but we do infact export the `getTasks` function:

https://github.com/graphile/worker/blob/fc58b7f0605350c224a7d2c9f765836c8f248691/src/getTasks.ts#L79

Here's an example of it being used in the Graphile Starter tests:

https://github.com/graphile/starter/blob/db6a5d61a67eebbba3bb6a479c8a267461b5a26f/%40app/db/__tests__/helpers.ts#L199-L203
