### ISSUE TITLE
Compatibility with supabase?

### ISSUE THREAD

**Issue by tonyxiao** [graphile/worker#295]
### Summary

In my supabase instance the worker doesn't seem to do anything (job just sits there without being run). Is there an extension / switch that needs to be turned on? When I tested on vanilla postgres on localhost everything seems to work just fine.  W

### Additional context

```bash
❯ npx graphile-worker -c $POSTGRES_URL
[core] INFO: Failed to read crontab file '/Users/tony/Code/usevenice/venice/crontab'; cron is disabled
[core] INFO: Worker connected and looking for jobs... (task names: 'hello')
```

Stuck there afterwards. I checked that there are jobs in the job table non-locked.

**Comment by benjie** [comment]
First thing I'd recommend checking is that you're connected to the right database. Given no errors have been output, it seems that the `graphile_worker` schema will have been created - so look for that in your database and see if it exists; if it does not then there may be a configuration issue somewhere.

**Comment by tonyxiao** [comment]
Yea the schema exists, and I can query it / add jobs to it. What else could be the cause of it?

**Comment by tonyxiao** [comment]
![CleanShot 2022-10-25 at 12 19 34@2x](https://user-images.githubusercontent.com/696842/197748649-6387625b-36d2-45dd-b7b5-a5a2eda2f139.png)
Ok figured out. for some reason the get_job function was missing (and the worker was not throwing any errors about it :( )

I dropped the schema and recreated it and now everything works. Very strange!

**Comment by tonyxiao** [comment]
Not sure how it got into this state, Hopefully it's not a red herring

**Comment by benjie** [comment]
Maybe you’re using a mixture of Worker versions… don’t do that ;)

**Comment by tonyxiao** [comment]
Hmm that's possible. I was using `npx` once and using it the explicit `graphile-worker` module a different time. The npm module uses 0.14.0-alpha by default. I wonder if `npx` uses the same

**Comment by psteinroe** [comment]
A few hints to properly integrate graphile-worker with supabase:
- Copy the migrations into `supabase/migrations` and run them as a normal migration. Make sure that you copy only the migrations valid for the graphile-worker version you are using, since the main branch is the latest version, not the latest stable version. Also make sure that you apply the migrations before connecting the first worker. 
- Make sure to set `noPreparedStatements: true` since supabase is using pgBouncer connection pooling.
