### ISSUE TITLE
Correct approach to change schedule of recurring tasks (crontab)

### ISSUE THREAD

**Issue by avzabr** [graphile/worker#318]
### Summary

I plan to use graphile worker as a library to run recurring tasks (crontab). At the same time there is a requirement to be able to change the schedule of task over UI and be able to stop reoccurring tasks from UI as well. 

Scenario 1: 
* Task has been running every 5 minutes: `*/5 * * * *`
* Admin has decided to change it to run every 10 minutes: `*/10 * * * *`

Scenario 2: 
* Task has been running every 5 minutes: `*/5 * * * *`
* Admin has decided to disable task

At the same time the schedule for other tasks should not be changed and Ideally only rescheduled task should be anyhow affected. 

As far I can see the only option now is to stop runner and recreate it: 
```
// after the schedule has been changed changed or job disabled
await existingRunner.stop();
const newRunner = await run({
        taskList: {
            cron1: async (payload, helpers) => {
                helpers.logger.info(`1`);
            },
            cron2: async (payload, helpers) => {
                helpers.logger.info(`2`);
            },
        },
        parsedCronItems: parseCronItems([{
            task: 'cron1,
            pattern: '*/5 * * * *', // <- update pattern
        }, {
            task: 'cron2',
            pattern: '*/10 * * * *',
        }]),
    });
await newRunner.promise;
```

In this case I assume all of the currently running jobs will be stopped after completion and runner recreated. 

Questions:
* Would this be correct approach to use for mentioned use case or there better suggestions? 
* If there is no way to do it currently could it be considered as a valuable feature to add support for reset of schedules:
  ```
  runner.setParsedCronItems();
  ```

**Comment by benjie** [comment]
We have watch mode that can update cron on the fly, but more importantly you can use the techniques that watch mode uses in order to keep cron up to date - namely mutating the `items` array directly: <https://github.com/graphile/worker/blob/9a817c1f1903abdda33236a89b72461793389c41/src/getCronItems.ts#L39> and it should Just Work ™️ 

---

I strongly urge you to use a stable `id` for each task, rather than letting that be assigned automatically, so that you don't get unexpected weirdness. See `opts` : https://github.com/graphile/worker/tree/9a817c1f1903abdda33236a89b72461793389c41#recurring-tasks-crontab
