### ISSUE TITLE
Add helper to permanently fail/complete locked jobs

### ISSUE THREAD

**Issue by codetheweb** [graphile/worker#328]
### Feature description

We manually keep track of worker health using the approach described [here](https://github.com/graphile/worker/issues/222#issuecomment-1347429067). If a worker dies while executing a job, we need a way to permanently fail the now-locked job (this is especially important when using queue names).

We currently use a helper like this to mutate data within the `graphile_worker` schema:

```ts
import { type Pool } from "pg"
import * as db from "zapatos/db"

export const permanentlyFailLockedJobs = async (
  job_ids: string[],
  pool: Pool
) => {
  await db.serializable(pool, async (trx) => {
    const deleted_jobs = await db
      .deletes(
        "graphile_worker.jobs",
        {
          id: db.conditions.isIn(job_ids.map(Number)),
        },
        {
          returning: ["id", "queue_name"],
        }
      )
      .run(trx)

    const queue_names_to_unlock = [
      ...new Set(deleted_jobs.map((job) => job.queue_name).filter(Boolean)),
    ] as string[]
    if (queue_names_to_unlock.length > 0) {
      await db
        .update(
          "graphile_worker.job_queues",
          {
            locked_at: null,
            locked_by: null,
          },
          {
            queue_name: db.conditions.isIn(queue_names_to_unlock),
          }
        )
        .run(trx)
    }
  })
}
```

Would it make sense for a helper to be added to Graphile Worker for this?

(This is a bit of a stopgap measure until https://github.com/graphile/worker/issues/222 is implemented.)

### Supporting development

- [x] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [ ] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
See also #222

**Comment by jakebiesinger-storyhealth** [comment]
@benjie "unlock jobs from a crashed worker" -- how would this interact with the return state of the worker job itself? 

Say the worker encounters an error which should not be retried. *As part of the execution* it would unlock the job and then permanently fail the job, but then it would either `return` (which looks like a job success) or it would `throw` (which looks like a job failure). If interpreted as a success, I wouldn't want the row to be disappeared (due to completion) but I also wouldn't want the `last_error` field to be changed from what I set it in the `permanently_fail_jobs` call.

Thoughts?

**Comment by jakebiesinger-storyhealth** [comment]
Answering my own question, the behavior of the current system is such that unlocking the row + then permanently failing the job must be followed by a `throw` from the worker -- a successful `return` will cause the row to disappear. On the plus side, the system currently retains the permanent failure reason in `last_error`, even if the `throw`n error is different.

**Comment by benjie** [comment]
> how would you suggest handling the case where the job encounters an unrecoverable, not-retriable error?

From the Worker point of view, that is success. The job should not be tried again, it has successfully completed all of the work that it could do (which, it turns out, was nothing). 

>  rather than having the failure record where all the other fails exist.

You should _not_ store perma-failed jobs in the jobs table. You should keep that table as empty as you can, otherwise you will suffer significant performance degradation over time. Please read this (currently unpublished) documentation on the subject:

https://github.com/graphile/worker/blob/main/website/docs/scaling.md

**Comment by benjie** [comment]
(Edited previous comment now website is published)

Also, you should not rely too much on the `jobs` table; see:

https://worker.graphile.org/docs/schema

**Comment by jakebiesinger-storyhealth** [comment]
Thanks for the insights. I hadn't seen the warnings around the private schema, and had been planning on querying the `jobs` table directly to support a simple job monitoring UI with a basic retry interface.

I realize it's off-topic for this page, but I might suggest either an administrative command for reading from the `jobs` table 
 or a view over `jobs`, providing some measure of insulation from your schema changes. If that sounds useful, I can open a separate ticket to discuss semantics and perhaps throw a PR your way.

**Comment by benjie** [comment]
We'd have to think about it carefully, but yes I think something like that would make sense; probably with a `SKIP LOCKED` added in. I probably should have done that in 0.14 when I replaced the jobs table... Probably should have left it there with a view and moved the jobs table somewhere else. Actually renaming the jobs table to something like `_jobs_private` and creating a view over it called `jobs` would make a lot of sense...

**Comment by benjie** [comment]
I might just go ahead and make it myself, I'm planning to spend a few more days on Worker before releasing 0.16. But if I don't get around to it (or if you think you can beat me to it!) please go ahead.

**Comment by jakebiesinger-storyhealth** [comment]
So fast! 🚤
