### ISSUE TITLE
Batch Jobs: execute on X number of payloads as well as run_at

### ISSUE THREAD

**Issue by ericallam** [graphile/worker#343]
### Feature description

Currently, batched jobs aggregate payloads in an array by job key and then are executed once the run_at value is reached. I would like for the ability for batched jobs to execute once they reach a "maximum payloads" number as well, whichever comes first.

### Motivating example

This would power the Trigger.dev "Batch Polling" ([link](https://github.com/triggerdotdev/trigger.dev/discussions/418)) feature where we would batch different polling tasks together to cut down on the amount of requests we are doing to clients. We can't really wait a certain interval because we can't "afford" to batch too much work together into one execution.  We could do this manually ourselves (say set the run_at to be 60 seconds, and then once that task executes we would break up the payloads array into X number of slices), but I'd rather do the work more immediately once X payloads are batched together to space up the execution.

### Breaking changes

I'm not sure about internals but this would require another Task option to be added I believe. Something like `batchMaxPayloads`.

### Supporting development

I:

- [ ] am interested in building this feature myself
- [x] am interested in collaborating on building this feature
- [x] am willing to help testing this feature before it's released
- [x] am willing to write a test-driven test suite for this feature (before it exists)
- [x] am a [Graphile sponsor](https://www.graphile.org/sponsor/) ❤️
- [ ] have an active [support or consultancy contract](https://www.graphile.org/support/) with Graphile

**Comment by benjie** [comment]
I'd really rather not add this as a core feature of Graphile Worker because it would require an after-insert check on every inserted row (to see if it has hit the max payloads) which would mean everyone incurs this cost even if they're not using the feature. Further, things get complex if you have a max of 10, an existing payload containing 9, and a new payload containing 2 - do you add one to the existing batch, queue it for execution, and then create a new batch, or do you go over the maximum and then execute that? Different people will want different things.

Instead, I suggest that you handle this in your own function, maybe something like:

```sql
create function your_schema_here.add_batch_job(
  job_key text,
  task_identifier text,
  payload json,
  maximum_payloads int,
  run_at timestamptz
) returns graphile_worker.jobs as $$
declare
  v_job graphile_worker.jobs;
begin
  if json_typeof(payload) is distinct from 'array' then
    raise exception 'Must only call add_batch_job with an array payload';
  end if;

  v_job := graphile_worker.add_job(
    identifier := task_identifier,
    payload := payload,
    run_at := run_at,
    job_key := job_key,
    job_key_mode := 'preserve_run_at' -- or 'replace' - up to you
  );
  
  if json_array_length(v_job.payload) >= maximum_payloads then
    update jobs set run_at = now() where jobs.id = v_job.id returning * into v_job;
    -- Optional: lie that this job was just inserted so a worker picks it up ASAP
    perform pg_notify('jobs:insert', '');
  fi;

  return v_job;
end
$$ language plpgsql volatile;
```

Thank you for your sponsorship :heart:
