### ISSUE TITLE
Is it possible to customise the backoff schedule / limit the number retries

### ISSUE THREAD

**Issue by philefstat** [graphile/worker#403]
### Summary

Is it possible to customise the backoff schedule / limit the number retries? 

### Additional context

For example, we use a worker to schedule messages to be sent via email and other channels to users. These may sometimes fail, e.g. the user has an incorrect number or there's an issue with the template. With the default amount of retries and backoffs, if those issues are corrected, the message may still get sent several days later - but at this point the message may no longer be relevant (or in fact, still sending it could misinform the user about the current status of a task). 

What's the recommended way to handle this? Ideally we'd like to retry a couple times, within a few hours, in case of a temporary outage, but not beyond that. 

Thanks for building a great system - overall it's a delight to work with graphile worker and it's fantastic to have our job queue living in the same db.

**Comment by benjie** [comment]
When you schedule a task, you may set its `max_attempts`: https://worker.graphile.org/docs/sql-add-job

However this is probably not the best way of doing it as it will leave lots of dead jobs in your jobs table, which will negatively impact performance. Instead, to solve both issues (limit attempts, control back-off (a bit)), you can just write the code into your task executor:

```ts
const myTask = (payload, helpers) => {
  const { job: { attempts } } = helpers;
  if (attempts > 1 && attempts < 4) {
    // Try again when attempts >= 4; i.e. after at least a minute
    throw new Error("Skipping to await a longer delay");
  }
  if (attempts > 12) {
    // Return success so that the job is deleted and never attempted again
    // TODO: do something about this - e.g. log the error somewhere, or notify the user, or whatever
    return;
  }

  await doTheThing(payload);
}
```

Note you can see the table at https://worker.graphile.org/docs/exponential-backoff to see the delays.

You can also use values like `job.created_at` to make decisions rather than the attempts number if you prefer.
