### ISSUE TITLE
Wrong WorkerUtils types?

### ISSUE THREAD

**Issue by christophemacabiau** [graphile/worker#414]
### Summary
in interfaces.d.ts
```js
export interface WorkerUtils extends Helpers {
  completeJobs: (ids: string[]) => Promise<DbJob[]>;
  permanentlyFailJobs: (ids: string[], reason?: string) => Promise<DbJob[]>;
  ...
}
```
which is not coherent with the sql
```sql
CREATE FUNCTION :GRAPHILE_WORKER_SCHEMA.complete_jobs(job_ids bigint[]) RETURNS SETOF :GRAPHILE_WORKER_SCHEMA._private_jobs
 ```
and with the [doc](https://worker.graphile.org/docs/admin-functions)
```js
const deletedJobs = await workerUtils.completeJobs([7, 99, 38674, ...]);
```

or maybe I am totally lost :-)

**Comment by benjie** [comment]
We use a `string` for bigints to ensure safety (the `number` type cannot safely store bigints (only safe up to `2^53 - 1`), bigint can go up to `2^63 - 1`), and using BigInt in JS is unnecessarily awkward since we don't need to do maths with it); so `interfaces.d.ts` and the SQL are indeed coherent. If you want to send a PR to the docs wrapping those IDs in quote marks that would be fine, but it's non-essential since `number` can be cast to `string` safely.

**Comment by christophemacabiau** [comment]
I agree... I had an error in typescript but I am unable to reproduce it.
