### ISSUE TITLE
How do I fetch the actual queue name from within a running task? 

### ISSUE THREAD

**Issue by pietvanzoen** [graphile/worker#423]
I'm in the process of upgrading to the new database schema (0.16.1). 

Previously `helpers.job.queue_name` was set to the actual queue name. Now you have `helpers.job.job_queue_id` which is set to the id of the queue record in the `_private_job_queues` table. 

How do I fetch the actual queue name from within a running task? 

Obviously querying the private table is risky, but I don't see an obvious helper in the docs to get the queue name.

**Comment by benjie** [comment]
I hadn't anticipated anyone using the queue name in a way where its value would be significant at task execution time; it's purpose relates only to scheduling. That said, I can now see use cases for it, for example if you want to return success but re-schedule the job for later, you might want to re-schedule it into the same queue.

This is a bit challenging, because when the worker starts up it knows all of the task identifiers it supports so it can get their IDs and then at runtime it can do an `O(1)` lookup in the hash table to see that the task identifier is for a given id. With queues, the same is not true - new queues could be added at any time (in early versions of Worker, they were auto-generated as UUIDs) so we can't do a single lookup table. Always doing a join when fetching the job not be ideal...

... I'm thinking we could add a `getQueueName()` method to helpers that would find the queue name for the job.queue_id either by looking up in the cache, or on failure by fetching that queue name from the DB. Ideally we'd put some smarts in it so that it does batching across multiple parallel calls. Alternatively we could just fetch an updated object from the DB; really depends how many queue names there are. Maybe on a cache miss we'd do a cleanup and then fetch all...

# :thinking:

**Comment by pietvanzoen** [comment]
> for example if you want to return success but re-schedule the job for later, you might want to re-schedule it into the same queue

This is exactly our use case. Good guess! 😄 

> we could add a getQueueName() method to helpers

Yeah this would work for our use case. We don't have many jobs that need to know the queue name so we wouldn't have much extra value from the queue name being in every `job` object as it was.

Thanks for the quick response and consideration. :)
