### ISSUE TITLE
Queue and failed jobs

### ISSUE THREAD

**Issue by gaetan-craft** [graphile/worker#493]
### Summary

I try to understand the behavior of queue with failed jobs. I have tasks running for several hosts. I want to execute a task once at a time on a given host. I'm thinking of using one queue_name per host. Tasks can run around 10 minutes. I want to be able to run tasks in parallel across different hosts so launch the cli with -j 4 for example. Tasks had to be run in the order they are sent on a given host. Some tasks are flaky and need to be relaunched in case of failure.

Are queues the way to go ? I did some tests and it seems that if some task fail the next one if already enqueued is tried not waiting for the previous to be successful.

Does it seems to be an interesting scheduling behavior to implement ?
As a workaround I can wrap my task in a loop waiting for success but it seems less clever

**Comment by benjie** [comment]
> if some task fail the next one if already enqueued is tried not waiting for the previous to be successful.

This is indeed by design - when a job fails it is put to the back of the queue. If you do not want this behavior, then you should make it so that the next job only gets queued when the previous job is completed (e.g. as the very last thing in the task executor function).

Wrapping the job with a loop will only solve your problem if your workers never crash, never shut down, and are never disconnected from the network.
