### ISSUE TITLE
Debouncing jobs

### ISSUE THREAD

**Issue by mrmurphy** [graphile/worker#59]
We're currently using https://github.com/timgit/pg-boss in production, and it has been solid, but the API is a bit complex. I love how simple the API for "worker" is, and I'm inclined to give it a try.

One feature we use regularly in Pg-boss that doesn't seem to be present yet in Worker is debouncing a job by name.

For example, I have a cron in my app that schedules a background job every 30 seconds, but if that job is already running, or if there's already one queued, I don't want to add another.

Would adding something like this seem inline with your goals for this project @benjie?

**Comment by benjie** [comment]
How I solve this particular problem is with a cron table; something like this:

```sql
create table cron (
  ts timestamptz primary key
);
```

and then I add a trigger that schedules cron jobs when a row is written to cron.

Then, importantly, I have the workers attempt to write to this cron table a _rounded_ timestamp; in your case it'd be rounded to the nearest 30 seconds:


```js
const ROUNDING_INTERVAL = 30000; // 30 seconds

const ts = Math.floor(Date.now() / ROUNDING_INTERVAL) * ROUNDING_INTERVAL;
await pgClient.query('insert into cron (ts) values ($1) on conflict do nothing', [ts]);
// Note the "do nothing" prevents this throwing if the record already exists
```

Does this help, or is there specifically something you'd like Graphile Worker to factor in that's a little more complex than this?

**Comment by mrmurphy** [comment]
Oh interesting. And then you clean up your cron table at some point? I see how that works, but I think it'd be discouraging to new users that it'd take multiple steps in a migration (new table, new trigger) as well as the cron application code to set that up.

Could a simple, user-friendly API for supporting this be allowing a parameter like `singleton: true` to `runner.addJob`? If `singleton` is specified, the runner silently does not add the job to the queue if there is a job in the queue already with the same name.

**Comment by benjie** [comment]
[Stream of consciousness]

Singleton is an interesting idea; for that we'd probably have to require that it has no payload so there's no ambiguity about what happens if you call it with different payloads? We'd also have to think about the repeat count because you might not want it failing 20 times to trigger 1 day delays; maybe it would only have 1 attempt. Maybe we'd just encourage you to only give it one attempt.

Maybe the singleton would be a task name / payload combo, actually. That'd work better for cron, and is still not ambiguous so long as we explain what singleton means. Maybe an alternative name such as `if_not_exists` (which is quite SQL-y).

I'm not keen to search over the entire job queue when filing these, it's not as efficient as doing it with a cron table approach. We could create a partial index on `task_name || payload` when `singleton is true`; that should mean performance of regular jobs is unaffected.

Thoughts?

**Comment by mrmurphy** [comment]
[response stream of consciousness]

I like the name `if_not_exists`! And I think that makes it clear that, no matter the payload situation, the new job won't get published if an old one is running.

As far as retries go, as a user I think I'd expect a singleton job not to retry at all. If it fails, it is abandoned, and the next time the job is fired off, the new job picks right up. But if this were the situation, and the API automatically disabled retries, a name like `singleton` would be more appropriate than `if_not_exists` since we'd be changing multiple behaviors at once.

Probably the simplest approach is to just provide `if_not_exists`, and tell the user in the documentation that they may also want to disable retries?

As far as the index goes, is there not already an index on task_name? It doesn't seem like we'd have to check the payload at all. If a non-failed job exists with the same name already, then the new job is not published, no matter its payload.

Ah it doesn't look like there's a `task-identifier` index already. If there were, seems like the insert statement could use a simple `on conflict(task_identifier) do nothing`?

**Comment by benjie** [comment]
I was thinking we might index on, for example, `task: 'cron', payload: {user_id: 27}` - that way different payloads would go into different singletons. Of course if you just want one singleton you can pass an empty payload.

---

It turns out that there's quite a lot of overlap between the requirements for this and those for #58. I've just been chatting with @gregplaysguitar and we're effectively proposing that we'll add some kind of optional "custom identifier" to the `add_job` function; when you use this the job with this custom_identifier would be created if it didn't already exist, or updated if it did. For this use case you could use the custom_identifier of `cron:${ROUNDED_TIMESTAMP}` with a run_at of ROUNDED_TIMESTAMP.

It's not quite as optimal as the `cron` table in your case as the multiple `add_job` calls would cause a row to be updated (even though the values themselves wouldn't actually change), though we could potentially avoid this by adding a relevant `WHERE` cluase; e.g. `ON CONFLICT (custom_identifier) DO UPDATE SET <value> = excluded.<value>, ... WHERE <any of the values differ>`.

@gregplaysguitar is going to write up a proposal in the coming days.

**Comment by mrmurphy** [comment]
Wonderful, thank you! I just threw it in a new project and I'm very happy with the simplicity of the design and experience overall.

**Comment by benjie** [comment]
Hey @mrmurphy have a read through #61 and let us know if you have any feedback/concerns.
