### ISSUE TITLE
RFC: Allow deletion and update of scheduled jobs

### ISSUE THREAD

**Issue by gregplaysguitar** [graphile/worker#61]
## Objective

- allow jobs scheduled for the future via `run_at` to be cancelled or updated prior to being run
- facilitate “singleton” jobs, where repeated scheduling of the same task results in only one eventual run
- Maintain full backwards compatibility

## Motivation

This change solves the issues raised in #58 and #59 - use cases:

### Update a scheduled job (#58)

- A “send push notification” task is scheduled for the start of an end user’s preferred window, e.g. 9am-5pm
- Before the notification is sent, the user changes their preferred window settings
- The previously scheduled notification should be updated to reflect the new preference

### Cancel a scheduled job (#58)

- A “send push notification” task is scheduled for a user as above
- Before the notification is sent, it is invalidated by a separate system
- The notification task should be deleted

### Debounce a cron-based job (#59)

- A cron process schedules a background job every 30 seconds
- If the job is already running, or if there's already one queued, an additional job should not be queued

#### `graphile_worker.add_job` 

An optional `job_key` argument will be added to this function, and it will be changed to use plpgsql to allow conditional logic. New function signature:

```diff
 create function graphile_worker.add_job(
   identifier text, 
   payload json = '{}', 
   queue_name text = public.gen_random_uuid()::text, 
   run_at timestamptz = now(), 
   max_attempts int = 25
+  ,job_key text = null
 ) returns graphile_worker.jobs;
```

##### If job_key is not provided

- The `add_job` behaviour will remain unchanged as a simple `insert` into `graphile_worker.jobs`

##### If job_key is provided

- The new job will overwrite **all details** of an existing job with the same key, using `insert ... on conflict`, only if the job is not locked for processing
- If the previous job is locked for processing, or completed, a new job will be scheduled
- ~~Note there is an edge case here, where a job has already been retrieved for processing, but not completed. In this case there is no way to schedule a new job, as would happen if the previous one was complete. The `on conflict ... where` clause will prevent the job details from changing, and the function will return an empty set - the calling code can use this return value to handle the case as needed. This case will be documented.~~ See https://github.com/graphile/worker/issues/61#issuecomment-568247838
- `jobs.attempts` will be reset to zero and `jobs.last_error` to null, under the assumption that past failures should not impact the lifecycle of the newly updated job.
- In a future update, a boolean argument could be added to determine whether existing jobs should be overwritten or not, i.e. on conflict `do update` vs `do nothing`

#### `graphile_worker.remove_job`

This new function will allow deletion of an existing job by `job_key`. Function signature:

```
create function remove_job(
  job_key text
) returns graphile_worker.jobs;
```

- Only jobs not already locked may be deleted. This means
  - jobs which a worker has already retrieved for processing cannot be deleted
  - there is no need to "unlock" the `job_queues` table the way [`complete_job`](https://github.com/graphile/worker/blob/17c420ca86f8609484eafec8fbb252eebbbc6730/sql/000001.sql#L135-L137) does
- If the `job_key` doesn't exist, or the job is already in progress, the function will do nothing and return an empty set

### Schema changes

1. Add a new nullable unique `key` column to the `graphile_worker.jobs` table:

   `alter table graphile_worker.jobs add column key text unique;`

   Full vs partial indexing for this column will be decided after profiling each option.

   Other column names considered were 

   - `idempotency_id` (misleading as job details may change if other arguments differ)
   - `job_id` (already used as a function argument, clashes with `jobs.id`)
   - `task_id` (clashes with `jobs.task_identifier`)

2. Add `locked_by` and `locked_at` columns to the jobs table, as per https://github.com/graphile/worker/issues/61#issuecomment-568247838

### Tests

New tests will prove that

- passing the same `job_key` to `add_job` multiple times results in one scheduled job
- future-scheduled jobs can be removed via `remove_job` and do not run
- jobs scheduled for now are not deleted or updated

### Performance implications

A write performance impact is expected from the additional column and unique index. However, this should only affect the opt-in new behaviour - if `job_key` is not specified, performance should stay the same as before.

Before/after performance characteristics will be determined and documented via the bundled [perfTest](https://github.com/graphile/worker/#performance) command.

### Alternatives considered

- Change the `jobs.id` to text, and allow the user to specify it, instead of a separate identifier (`job_key`). Rejected due to unknown impact on read performance, and backwards incompatibility
- Store `jobs.id` value as returned by `add_job` in a separate table, external to the library, and use that to update/remove jobs. Rejected due to additional complexity and statefulness required in the implementing code, and because the problem is general enough to be a valuable library addition

### Questions / discussion

- Is there any solution to the edge case noted when updating a job which is already processing?
- Which additional tests, if any, should be written?

**Comment by benjie** [comment]
Excellent spec, thanks for taking this on! Here's some thoughts

### if job_key is provided, bullet 1

With this "only if `run_at` is in the future" constraint, cron tasks should be scheduled in the future (i.e. using Math.ceil in [this comment](https://github.com/graphile/worker/issues/59#issuecomment-567673375) rather than Math.floor.)

I'm not sure this "run_at is in the future" constraint is actually required; what benefit do you think it bestows? Perhaps a simple "is not locked" as in bullet 2 is sufficient?

### if job_key is provided, bullet 2

I had concerns about this, particularly relating to failed jobs, but bullet 3 addresses this by resetting `attempts`. I've edited the text to also reset the `last_error` field, as having `attempts=0` but `last_error` non-null would be confusing. Resetting these both also makes a lot of sense when it comes to debugging - seeing a `last_error` that relates to a different task/payload could be very confusing if you didn't realise it had been edited.

### if job_key is provided, bullet 4

This is certainly a possibility. I think if we adopt the "don't update where no values change" approach I mentioned in [this comment](https://github.com/graphile/worker/issues/59#issuecomment-567673375) then we might never need this - just have to be sure we always pass the same values.

On this note, the `queue_name` is currently generated randomly unless specified. When we update a task we'd also be moving it to another queue in the current proposal (unless the user specifies a queue_name). I think we should avoid this in case we partition on queue_name, so we should make the `add_job` function argument default to `null`, and then `coalesce(...)` in the relevant places.

### graphile_worker.remove_job :heavy_check_mark: 

Ah, "naming things". It's clear it shouldn't be called "delete_job" as that's not a match for "add_job". However, I wonder if "cancel_job" might be a better name. However, if you call it on a job that's failed permanently (i.e. max_attempts=25, attempts=25) then you're not really cancelling it... So perhaps "remove" is indeed more accurate. Let's stick with your proposal.

### graphile_worker.remove_job, bullet 1

Let's replace the `run_at` clause with simply "is not locked". It's possible the job queues could be a long way behind, it makes sense to allow people to cancel (or replace) jobs that haven't ran yet even if running them is overdue. Also be aware that we only poll the database every 15 seconds, so future scheduled jobs typically run between 0 and 15 seconds after their scheduled slot (this differs from normal jobs which typically start executing within a couple milliseconds).

### Schema changes

"jobs.job_key" seems redundant; could we just go with "jobs.key"? I originally proposed `custom_identifier` and `external_identifier` but agree they get confusing with `task_identifier`. I'm not super happy with `key` but it seems the best option we have right now; if anyone else has better ideas please raise them in the comments below.

Rather than just using a `unique` constraint here; perhaps it would be better to use a partial unique index - that way the rows with no job_key will be explicitly unindexed. I'm not sure of the performance differences (if any) between a unique index including nulls, and a unique partial index excluding nulls. If no-one can confirm either way lets stick to your proposal as it's simpler.

### Other concerns

If users don't make `job_key` sufficiently unique, then currently they can completely overwrite existing tasks with completely different tasks. This could cause trouble.

**Comment by benjie** [comment]
(Sidenote: it's nice that GitHub has issue revision history now, so you can see the edits I made.)

**Comment by mrmurphy** [comment]
I love the clarity and detail of this proposal. Way to go!

- I agree with @benjie on `is_not_locked` vs `run_at` being in the future.
- Even thought `job_key` is feels redundant to type, it's also the most descriptive and simple name I can think of as well, so it's got my vote.

Thanks for the fast responses to these issues!

**Comment by singingwolfboy** [comment]
> Change the `jobs.id` to text, and allow the user to specify it, instead of a separate identifier (`job_key`). Rejected due to unknown impact on read performance, and backwards incompatibility.

I like this alternative, and I much prefer the name `id` rather than `key`. I don't think that backwards incompatibility is a concern, considering all the warnings that Graphile Worker is still alpha software, and should not be considered stable yet.

Can someone more knowledgeable than me speak to the performance impact of this change? Also, would this mean that specifying an `id` would be _required_ when calling `add_job()`? I don't think that's a problem (since again, I don't think that backwards incompatibility is a concern right now), but it would be a good thing to note.

**Comment by garcianavalon** [comment]
Awesome spec, great write up @gregplaysguitar 👏 

Regarding the proposed changes to `graphile_worker.add_job`, I would like to understand the reasoning on why modifying the existing job, instead of marking "cancelled" or "rescheduled" the previous job and creating a new one. From a monitoring/sys admin perspective, having jobs mutate when I create a new one feels magical, non-intuitive and hard to trace. Maybe it's the naming of the function what is confusing me, why not have a `reschedule` function and leave `add_job` as is?? 

Regarding `graphile_worker.remove_job`, although the proposed behaviour looks good, I would like to suggest the possibility to instead of remove, to `cancel` the job. Instead of deleting the row, I think it is important to have a historical view of the jobs and what happened to each one. 

Now that I write this down, maybe `remove` is fine if the API also allows to `pause` a job. An example use case would be a job that calls another service that is down. I would like to pause the job retries until the service is back up and running to avoid getting more error traces and alerts.

**Comment by benjie** [comment]
@singingwolfboy I think you might be confusing the alpha status with migrate; worker is intended to be fairly stable. We’re 0.x so we _can_ break things, but I don’t think we need to, and performance wise I prefer the bigserial PK currently with arbitrary text partial secondary unique key separate.

**Comment by benjie** [comment]
@garcianavalon leaving completed jobs around reduces performance of the row scanning; I suggest if you need an audit trail to add triggers to maintain an audit table.

Regarding “pausing” a job, with this proposal that’d be just updating its run_at to some time in the future. You could also use this update functionality to tweak the payload (e.g. add/remove extra data), or to change the priority, or even to push the job onto a different queue. That’s why we’re not adding a “reschedule” method, otherwise we’d need a new method for each of the things and it’d become much more complex/larger surface area.

If we wanted the id (pk) to be the unique key then this would also prevent marking the “cancelled” status because adding a new job with same ID would be a unique key violation. Using a separate key as we propose gives us the flexibility to add this in future without breaking back-compat; but I don’t think we want this currently - we should keep churn low for performance if possible.

**Comment by benjie** [comment]
Great feedback everyone, keep it coming!

**Comment by gregplaysguitar** [comment]
@benjie @mrmurphy @singingwolfboy @garcianavalon thanks all for the great feedback! There's a few things to address, I'll try to cover everything but please let me know if I've missed anything.

## `run_at` vs "is not locked"

Apologies, I should have included the rationale for this decision originally. In the current schema, it's actually not possible to determine if a specific job is locked, because a queue may have multiple jobs. I wanted to avoid schema changes, and thought the `run_at` check was sufficient. Reconsidering though, I agree that "is not locked" is the optimal behaviour, so we'll need some changes.

My proposal is that we add `locked_at` and `locked_by` columns to the jobs table. These would be set alongside those in `job_queues`, which is redundant, but there's a significant benefit in that we don't have to use a join to determine if the job is locked. I also considered adding a `job_id` column to `job_queues`, but this seems like a worse redundancy and gives no performance gain.

With these columns added, `add_job` and `remove_job` would only update/delete an existing job if its `locked_at` column was null. 

I think this change also opens up some other possible optimisations regarding queues, but I'll raise those in another issue! Keen to hear any feedback on this idea.

## Modifying jobs in progress

Regarding the edge case I mentioned, I actually think we can able to handle this internally to the library, but first we should agree on the desired behaviour. Considering the following sequence

1. Job added
2. Job locked for processing
3. Job completed and removed

Update/removal behaviour prior to 2, or after 3, seems pretty obvious:

- before 2, modify the existing job
- after 3, create a new job 

_Between 2 and 3_ is where it gets tricky. I propose that in this case, 

- A new job should be scheduled exactly as it would if the current one was completed 
- The in-progress job should be flagged to prevent any retries, in the event of failure

This means a job update with a new payload is 

1. guaranteed to run
2. guaranteed to run _after_ the old version, if both end up getting processed

Does that sound reasonable?

## Other comments

> When we update a task we'd also be moving it to another queue in the current proposal ... I think we should avoid this in case we partition on queue_name

Agree, and makes sense

> Rather than just using a unique constraint here; perhaps it would be better to use a partial unique index

Intuitively, I'm not sure the partial would be necessary here? But let's profile it once we start on implementation and decide that way

> If users don't make job_key sufficiently unique, then currently they can completely overwrite existing tasks with completely different tasks.

I'm not sure there's anything we can do to guard against this, other than document it? This is how I would expect it to behave in any case, but keen to hear any ideas

**Comment by garcianavalon** [comment]
@benjie Thanks for the explanation. I agree on deleting jobs in the table then. 

The pause job solution doesn't sound very good though. I understand why you don't like having specific methods for each action and just expose a single entry point through `add_job` and thats ok but I think the API should provide a more explicit way of pausing a job than setting `run_at` in the future. That said, setting the date to the far future will work, so maybe I'm just being picky 😅 

@gregplaysguitar the modifying a job in progress logic proposed sounds reasonable to me 👍

**Comment by garcianavalon** [comment]
Today I found a task I can't solve without this API 🤦‍♂ Looking forward to its implementation!

**Comment by benjie** [comment]
I think “pausing” a job isn’t really desired. Delete the job and write the details elsewhere. Later, when unpausing, add it again. The jobs table should remain small if possible.

**Comment by garcianavalon** [comment]
Fair enough @benjie All LGTM then 👌

**Comment by gregplaysguitar** [comment]
Hi all, thanks for all the input - I'm back from my summer break now so will start implementation on this in the next few days. Let me know if there's any other thoughts, or concerns.

**Comment by gregplaysguitar** [comment]
@benjie and others - PR #63 is ready for review when you have time.

**Comment by benjie** [comment]
Awesome; I've added it to my calendar for Friday :+1:
