### ISSUE TITLE
Make `process.kill` optional

### ISSUE THREAD

**Issue by ffissore** [graphile/worker#84]
We use `graphile-worker` as a lib, as part of a more complex module. Shutting it down gracefully requires shutting down several components in order

With `graphile-worker` (0.4.0) we are no longer able to shut down our module gracefully, due to `registerSignalHandlers` [killing the current process](https://github.com/graphile/worker/blob/master/src/main.ts#L63)

**Comment by benjie** [comment]
I think it would be better to handle this in your code. Currently we "absorb" that particular signal until we've dealt with it, and then we stop absorbing it and trigger the signal again. Your code, presumably, also has signal handling code but my guess is it stops listening for the signal after one event. If you follow the same pattern as in graphile-worker (i.e. start acting on the first signal, ignore all further signals, and then stop ignoring the signal and re-trigger it when you're done) you should find it works smoothly.

I'd be happy to accept a PR that adds an option to stop us handling signals entirely, but I would not be happy simply not triggering the signal again as that could lead to the process never closing.

**Comment by ffissore** [comment]
Hi @benjie and thx for the reply. I'm a bit puzzled.

Have I understood correctly that you're suggesting to change how we handle signals to adapt to how graphile worker handles them? What if you change how you handle them in a future release, forcing us to adapt again?

Runner has a `stop` method that we call in our signal handler: why isn't that enough for shutting down gracefully? Could it be changed so that shutting down is delegated to your library users?

**Comment by benjie** [comment]
> Have I understood correctly that you're suggesting to change how we handle signals to adapt to how graphile worker handles them? What if you change how you handle them in a future release, forcing us to adapt again?

I'm more suggesting that you generalise the way you handle signals to maximise compatibility rather than you specifically adapt it to work with Graphile Worker. I don't think we handle signals in a particularly non-standard way. I can't imagine we'd change our signal handling in a way where handling signals in the way I've described would no longer work.

> Runner has a stop method that we call in our signal handler: why isn't that enough for shutting down gracefully? Could it be changed so that shutting down is delegated to your library users?

Yes, that's exactly what I'm suggesting you raise a PR for - give us a flag so that we *completely stop handling signals* and then you can call our stop method from your own handler. Basically what I'm saying is add an option to never call `registerSignalHandlers`.
